version: "1.0"
stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "andres-caylent/poc-monorepo"
    revision: "${{CF_BRANCH}}"
    git: "andres-caylent"
    stage: "clone"

  build:
    title: "Building container image"
    type: "build"
    arguments:
      working_directory: "${{clone}}"
      image_name: "lucerozuazquita/monorepo"
      tags:
      - ${{CF_REVISION}}
      - ${{CF_BRANCH_TAG_NORMALIZED}}
      registry: docker-hub
      dockerfile: "Dockerfile"
    stage: build    